%YAML 1.1
---
# Snapcraft Recipe for FileZilla
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: filezilla
summary: The free FTP client solution
icon: snap/gui/filezilla.svg
description: |
  This is the unofficial snap of FileZilla®, the free FTP solution. The FileZilla Client not only supports FTP, but also FTP over TLS (FTPS) and SFTP. It is open source software distributed free of charge under the terms of the GNU General Public License.

  This is NOT an official distribution of FileZilla, refer the issue tracker for any issues regarding the use of this snap:

      https://github.com/Lin-Buo-Ren/filezilla-snap/issues

version: determined-by-version-script
version-script: ./snap/local/build-utilities/set-snap-version.bash

confinement: devmode
grade: devel

plugs:
  # For snaps with a graphical user interface:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Network access
  network:

apps:
  filezilla:
    command: >
      bin/desktop-launch
      "${SNAP}"/bin/filezilla-launch
      "${SNAP}"/bin/filezilla
    desktop: share/applications/filezilla.desktop

parts:
  # Utility programs to help with package building
  build-utilities:
    source: snap/local/build-utilities
    plugin: dump
    organize:
      '*': assets/build-utilities/
    prime:
    - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  # Program patches to solve issues that can't be solved by tweaking in runtime
  #patches:
    #source: snap/local/patches
    #plugin: dump
    #organize:
      #'*': assets/patches/
    #prime:
    #- -*

  # Helper programs that can be called at snap runtime
  #helpers:
    #source: snap/local/helpers
    #plugin: dump
    #organize:
      #'*': bin/
    #stage:
    #- -bin/README.*

  # Remote part for recording the exact revision for each part during building
  #parts-meta-info:

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  #desktop-gtk3:

  # Optional auxiliary part for displaying simple dialogs for better user experience, powered by Zenity
  # https://forum.snapcraft.io/t/the-zenity-remote-part/8793
  #zenity:
    # This part or part recipe is needed until LP#1766878 is fixed
    #
    # Bug #1766878 “$SNAPCRAFT_PROJECT_NAME used in a remote part expands to wrong value” : Bugs : Snapcraft
    # https://bugs.launchpad.net/snapcraft/+bug/1766878
    #configflags:
    #- --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
    #- --disable-libnotify
    #- --disable-webkitgtk
    #organize:
      #snap/$SNAPCRAFT_PROJECT_NAME/current: /

  libfilezilla:
    after:
    # For speeding up build
    - ccache

    source: https://download.filezilla-project.org/libfilezilla/libfilezilla-0.15.1.tar.bz2
    source-checksum: sha512/d557f7636bfc3958b8558fab3384b0ea84caea594566d39c051f20f02dfd71213369c50df282a3f7d2dd757038bd26e9722214839dab965cb7cde9733d59883a
    #source: https://svn.filezilla-project.org/svn/libfilezilla/tags/0.15.1
    #source-type: svn

    plugin: autotools
    build-packages:
    # DISABLED: Documentation
    #- doxygen
    #- texlive-latex-base

    - g++

    # DISABLED: Unittests
    #- libcppunit-dev

    - nettle-dev
    - pkg-config

    filesets:
      #FIXME: Documentation files not appeared in installdir
      library-headers:
      - include
      library-libtool:
      - lib/*.la
      library-pkgconfig:
      - lib/pkgconfig
      library-shared:
      - lib/**.so*
      library-static:
      - lib/**.a

    prime:
    - $library-shared

  filezilla:
    after:
    - build-utilities # for patch-desktop-entries.*

    source: https://svn.filezilla-project.org/svn/FileZilla3/tags/3.39.0
    source-type: svn

    plugin: nil

    override-stage: |
      set \
        -o errexit \
        -o nounset

      snapcraftctl stage

      ./assets/build-utilities/patch-desktop-entries.bash
