%YAML 1.1
---
# Snapcraft Recipe for FileZilla
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: filezilla-brlin
summary: The free FTP client solution
icon: snap/gui/filezilla.svg
description: |
  This is the unofficial snap of FileZilla®, the free FTP solution. The FileZilla Client not only supports FTP, but also FTP over TLS (FTPS) and SFTP. It is open source software distributed free of charge under the terms of the GNU General Public License.

  This is NOT an official distribution of FileZilla, refer the issue tracker for any issues regarding the use of this snap:

      https://github.com/Lin-Buo-Ren/filezilla-snap/issues

version: determined-by-version-script
version-script: ./snap/local/build-utilities/set-snap-version.bash

confinement: devmode
grade: devel

plugs:
  # For snaps with a graphical user interface:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Network access
  network:

  # gtk-common-themes
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

  # Inhibit power management
  screen-inhibit-control:

apps:
  filezilla-brlin:
    command: >
      bin/desktop-launch
      "${SNAP}"/bin/filezilla-launch
      "${SNAP}"/bin/filezilla
    desktop: share/applications/filezilla.desktop

parts:
  # Utility programs to help with package building
  build-utilities:
    source: snap/local/build-utilities
    plugin: dump
    organize:
      '*': assets/build-utilities/
    prime:
    - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  # Program patches to solve issues that can't be solved by tweaking in runtime
  #patches:
    #source: snap/local/patches
    #plugin: dump
    #organize:
      #'*': assets/patches/
    #prime:
    #- -*

  # Helper programs that can be called at snap runtime
  #helpers:
    #source: snap/local/helpers
    #plugin: dump
    #organize:
      #'*': bin/
    #stage:
    #- -bin/README.*

  # Remote part for recording the exact revision for each part during building
  parts-meta-info:

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-gtk3:

  # Optional auxiliary part for displaying simple dialogs for better user experience, powered by Zenity
  # https://forum.snapcraft.io/t/the-zenity-remote-part/8793
  zenity:
    after:
    - ccache

    # This part or part recipe is needed until LP#1766878 is fixed
    #
    # Bug #1766878 “$SNAPCRAFT_PROJECT_NAME used in a remote part expands to wrong value” : Bugs : Snapcraft
    # https://bugs.launchpad.net/snapcraft/+bug/1766878
    configflags:
    - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
    - --disable-libnotify
    - --disable-webkitgtk
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /

  libfilezilla:
    after:
    # For speeding up build
    - ccache

    source: https://download.filezilla-project.org/libfilezilla/libfilezilla-0.15.1.tar.bz2
    source-checksum: sha512/d557f7636bfc3958b8558fab3384b0ea84caea594566d39c051f20f02dfd71213369c50df282a3f7d2dd757038bd26e9722214839dab965cb7cde9733d59883a
    #source: https://svn.filezilla-project.org/svn/libfilezilla/tags/0.15.1
    #source-type: svn

    plugin: autotools
    build-packages:
    # DISABLED: Documentation
    #- doxygen
    #- texlive-latex-base

    - g++

    # DISABLED: Unittests
    #- libcppunit-dev

    - nettle-dev
    - pkg-config

    filesets:
      #FIXME: Documentation files not appeared in installdir
      library-headers:
      - include
      library-libtool:
      - lib/*.la
      library-pkgconfig:
      - lib/pkgconfig
      library-shared:
      - lib/**.so*
      library-static:
      - lib/**.a

    prime:
    - $library-shared

  # Remote part for a recent wxWidgets 3.0.X distribution
  wxwidgets-3-0:
    after:
    - ccache

  nettle:
    after:
    - ccache

    source: https://git.lysator.liu.se/nettle/nettle.git
    source-branch: release-3.4-fixes
    source-depth: 1

    plugin: autotools
    build-packages:
    # Documentation
    - ghostscript
    - texinfo
    - texlive

    # Public key crypto
    - libgmp-dev

    filesets:
      docs-info:
      - share/info/*.info
      docs-info-exclude:
      - -share/info/dir
      executables:
      - bin
      library-headers:
      - include
      library-pkgconfig:
      - lib/pkgconfig
      library-shared:
      - lib/**.so*
      library-static:
      - lib/**.a

    stage:
    - $docs-info-exclude

    prime:
    - $library-shared

  libtasn1:
    after:
    - ccache

    source: https://gitlab.com/gnutls/libtasn1.git
    # Maintenance branch not yet available
    #source-branch: libtasn1_4_x
    source-tag: libtasn1_4_13
    source-depth: 1

    # https://gitlab.com/gnutls/libtasn1/blob/master/README-alpha
    plugin: make
    build-packages:
    - bison
    - help2man
    - gtk-doc-tools
    - libtool
    - texinfo
    - texlive
    - texlive-extra-utils
    - texlive-generic-recommended
    - valgrind

    override-build: |
      set \
        -o errexit \
        -o nounset

      env ADDFLAGS=--prefix= \
        make bootstrap

      snapcraftctl build

    filesets:
      docs-gtk:
      - share/gtk-doc
      docs-info:
      - share/info/*.info
      docs-info-exclude:
      - -share/info/dir
      docs-man:
      - share/man
      executables:
      - bin
      library-headers:
      - include
      library-libtool:
      - lib/**.la
      library-pkgconfig:
      - lib/pkgconfig
      library-shared:
      - lib/**.so*
      library-static:
      - lib/**.a

    stage:
    - $docs-info-exclude

    prime:
    - $library-shared

  gnutls:
    after:
    - ccache
    - nettle
    - libtasn1

    source: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.5.tar.xz

    # DISABLED: submoduule too much history :(
    #source: https://gitlab.com/gnutls/gnutls.git
    #source-depth: 1

    # Not created yet
    #source-branch: gnutls_3_6_x

    #source-tag: gnutls_3_6_5

    plugin: autotools
    # https://www.gnutls.org/download.html
    build-packages:
    - autogen

    - gperf

    # Guile bindings
    - guile-2.0-dev

    # Too old in Ubuntu 16.04(4.7), use libtasn1 part
    #- libtasn1-6-dev

    # Unit testing framework dependency
    - libcmocka-dev

    - libidn2-0-dev
    - libp11-kit-dev

    # Trousers(TPM Support)
    - libtspi-dev

    - libunbound-dev
    - libunistring-dev

    # Too old in Ubuntu 16.04(3.2), use nettle part
    #- nettle-dev

    - pkg-config

    stage-packages:
    - libidn2-0
    - libopts25
    - libunbound2

    filesets:
      docs-info:
      - share/info
      - -share/info/dir
      docs-manpages:
      - share/man
      docs-misc:
      - share/doc
      executables:
      - bin
      library-bindings-guile:
      - lib/guile
      - share/guile
      library-headers:
      - include
      library-libtool:
      - lib/**.la
      - -lib/guile
      library-pkgconfig:
      - lib/pkgconfig
      library-shared:
      - lib/**.so*
      - -lib/guile
      library-static:
      - lib/**.a
      localization:
      - share/locale

    prime:
    - $executables
    - $library-shared
    - $localization

  filezilla:
    after:
    # For patch-desktop-entries.*
    - build-utilities

    # For speeding up build
    - ccache

    - gnutls
    - libfilezilla
    - wxwidgets-3-0

    source: https://download.filezilla-project.org/client/FileZilla_3.39.0_src.tar.bz2
    source-checksum: sha256/fb515e93775e5ad94ff2755b39605b62b3e8fcfc1125757f411d8f580d16444f
    #source: https://svn.filezilla-project.org/svn/FileZilla3/tags/3.39.0
    #source: https://svn.filezilla-project.org/svn/FileZilla3/trunk
    #source-type: svn

    plugin: autotools
    configflags:
    # Speed up one-time build
    - --disable-dependency-tracking

    # Conflict with ccache
    - --disable-precomp

    # No use for snap(we still allow manual update check though)
    - --disable-autoupdatecheck

    build-packages:
    # The libgnutls distribution in Ubuntu 16.04 is too old(3.4.10)
    #- libgnutls-dev

    - libpugixml-dev
    - libsqlite3-dev

    # The wxWidgets distribution in Ubuntu 16.04 is too old(3.0.2)
    #- libwxgtk3.0-dev

    - pkg-config

    stage-packages:
    - libnotify4
    - libpugixml1v5
    - libsm6
    - libxxf86vm1

    filesets:
      executables:
      - bin
      docs-manpages:
      - share/man
      share-appdata:
      - share/appdata
      share-desktop-entries:
      - share/applications
      share-filezilla:
      - share/filezilla
      share-icons:
      - share/icons
      share-pixmaps:
      - share/pixmaps
      localization:
      - share/locale

    override-stage: |
      set \
        -o errexit \
        -o nounset

      snapcraftctl stage

      ./assets/build-utilities/patch-desktop-entries.bash
